#ifndef _STUB_STDIO_H
#define _STUB_STDIO_H
/* Declarations only. We compile with -S and never link, so the RISC-V gadget
   code below main() is generated by a real RISC-V compiler; only the harness's
   libc calls are left as unresolved externs. */
typedef struct _IO_FILE FILE;
extern FILE *stdout, *stderr, *stdin;
int printf(const char *, ...);
int fprintf(FILE *, const char *, ...);
int sprintf(char *, const char *, ...);
int puts(const char *);
int putchar(int);
int fflush(FILE *);
FILE *fopen(const char *, const char *);
int fclose(FILE *);
int fputs(const char *, FILE *);
#define NULL ((void*)0)
#endif
